version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - APP_NAME=${APP_NAME:-AI Powered HR Assistant}
      - DEBUG=${DEBUG:-False}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY:-}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID:-}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - SENDER_EMAIL=${SENDER_EMAIL:-noreply@example.com}
      - SENDER_NAME=${SENDER_NAME:-HR Recruitment System}
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
      - results:/app/results
    restart: unless-stopped
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dokploy-network:
    external: true

volumes:
  uploads:
  logs:
  results:
